Traceback (most recent call last):
  File "/scratch/ierez/IGMCosmo/VoidFinder/scripts/VoidFinder_DR16S82_deltafields_numcpus3.py", line 32, in <module>
    from vast.voidfinder import find_voids, filter_data
  File "/home/ierez/.local/lib/python3.8/site-packages/vast_voidfinder-0.3.9-py3.8-linux-x86_64.egg/vast/voidfinder/__init__.py", line 17, in <module>
    from .voidfinder import filter_data, \
  File "/home/ierez/.local/lib/python3.8/site-packages/vast_voidfinder-0.3.9-py3.8-linux-x86_64.egg/vast/voidfinder/voidfinder.py", line 14, in <module>
    from .hole_combine import combine_holes, combine_holes_2
  File "/home/ierez/.local/lib/python3.8/site-packages/vast_voidfinder-0.3.9-py3.8-linux-x86_64.egg/vast/voidfinder/hole_combine.py", line 12, in <module>
    from ._hole_combine_cython import remove_duplicates_2, \
  File "vast/voidfinder/_hole_combine_cython.pyx", line 2, in init vast.voidfinder._hole_combine_cython
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
